import type { Avatar } from "@/types/avatar"

export const avatars: Avatar[] = [
  {
    id: "1",
    name: "Ava SEO",
    role: "SEO Specialist",
    functions: ["Keyword Research", "Content Optimization", "Backlink Analysis", "Technical SEO Audits"],
    image: "https://avatar.iran.liara.run/public/45",
    requiredPlan: "small",
  },
  {
    id: "2",
    name: "Mark Ads",
    role: "Ads Campaign Manager",
    functions: ["PPC Strategy", "Ad Copywriting", "Audience Targeting", "Performance Tracking"],
    image: "https://avatar.iran.liara.run/public/46",
    requiredPlan: "small",
  },
  {
    id: "3",
    name: "Ulysses UX",
    role: "UX Designer",
    functions: ["User Research", "Wireframing", "Prototyping", "Usability Testing"],
    image: "https://avatar.iran.liara.run/public/47",
    requiredPlan: "small",
  },
  {
    id: "4",
    name: "Penelope Copy",
    role: "Copywriter",
    functions: ["Sales Copy", "Blog Posts", "Website Content", "Email Campaigns"],
    image: "https://avatar.iran.liara.run/public/48",
    requiredPlan: "medium",
  },
  {
    id: "5",
    name: "Data Dan",
    role: "Data Analyst",
    functions: ["Market Research", "Trend Analysis", "Reporting", "Predictive Modeling"],
    image: "https://avatar.iran.liara.run/public/49",
    requiredPlan: "medium",
  },
  {
    id: "6",
    name: "Social Sam",
    role: "Social Media Strategist",
    functions: ["Content Calendar", "Engagement Tactics", "Platform Management", "Influencer Outreach"],
    image: "https://avatar.iran.liara.run/public/50",
    requiredPlan: "medium",
  },
  {
    id: "7",
    name: "Devon Dev",
    role: "Web Developer",
    functions: ["Frontend Development", "Backend Integration", "API Development", "Performance Optimization"],
    image: "https://avatar.iran.liara.run/public/51",
    requiredPlan: "big",
  },
  {
    id: "8",
    name: "Content Carla",
    role: "Content Strategist",
    functions: ["Content Planning", "Editorial Calendar", "Audience Segmentation", "Distribution Channels"],
    image: "https://avatar.iran.liara.run/public/52",
    requiredPlan: "big",
  },
  {
    id: "9",
    name: "PR Paul",
    role: "Public Relations Expert",
    functions: ["Media Relations", "Crisis Management", "Press Release Writing", "Brand Reputation"],
    image: "https://avatar.iran.liara.run/public/53",
    requiredPlan: "big",
  },
  {
    id: "10",
    name: "Legal Leo",
    role: "Legal Advisor",
    functions: ["Compliance Checks", "Contract Review", "Intellectual Property", "Privacy Policies"],
    image: "https://avatar.iran.liara.run/public/54",
    requiredPlan: "big",
  },
]
